codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "tests/"
  - "src/spectrakit/cli.py"
  - "src/spectrakit/contrib/"
  - "src/spectrakit/plot.py"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  unittests:
    paths:
      - src/spectrakit/
    carryforward: true
